### ISSUE TITLE
[INFO] Universal 2 binary

### ISSUE THREAD

**Issue by JayBrown** [FigBug/imguru#6]
Will there be an arm64+x86_64 universal binary of imguru?

**Comment by JayBrown** [comment]
I've now managed to build a universal binary for macOS 11.1. I've stuck to TinyXML, even though there's already **TinyXML2** available here: https://github.com/leethomason/tinyxml2

There are three deprecation warnings, all of them regarding `bestRepresentationForDevice` in `NSImageAdditions.m`:

```
- (null_unspecified NSImageRep *)bestRepresentationForDevice:(null_unspecified NSDictionary *)deviceDescription
API_DEPRECATED("Use -[NSImage bestRepresentationForRect:context:hints:] instead.
Any deviceDescription dictionary is also a valid hints dictionary.", macos(10.0,10.6));
```

But I didn't know how to fix those. All the other warnings can be auto-fixed by Xcode.

`libcurl.dylib` needs to be substituted for `libcurl.tbd` (nested in Xcode).

**ONE PROBLEM encountered:** after uploading to imgur, imguru's stdout (i.e. the imgur URL), and possibly also the pasteboard copy, contains a newline character, so I'm currently not executing

`imguru foo`

but

`imguru foo | grep -v "^$"`

Don't know how to fix that. (?)

[imguru.tar.gz](https://github.com/FigBug/imguru/files/6068874/imguru.tar.gz)

**Comment by FigBug** [comment]
Added Apple Silicon support in latest build. Also notarized.
